//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viridian.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class ComputerSystem : global::System.Configuration.ApplicationSettingsBase {
        
        private static ComputerSystem defaultInstance = ((ComputerSystem)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ComputerSystem())));
        
        public static ComputerSystem Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Virtual Computer System")]
        public string MicrosoftVirtualComputerSystem {
            get {
                return ((string)(this["MicrosoftVirtualComputerSystem"]));
            }
            set {
                this["MicrosoftVirtualComputerSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Hosting Computer System")]
        public string MicrosoftHostingComputerSystem {
            get {
                return ((string)(this["MicrosoftHostingComputerSystem"]));
            }
            set {
                this["MicrosoftHostingComputerSystem"] = value;
            }
        }
    }
}
