//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viridian.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Exceptions : global::System.Configuration.ApplicationSettingsBase {
        
        private static Exceptions defaultInstance = ((Exceptions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Exceptions())));
        
        public static Exceptions Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Class name does not match!")]
        public string ClassNameExceptionMessage {
            get {
                return ((string)(this["ClassNameExceptionMessage"]));
            }
            set {
                this["ClassNameExceptionMessage"] = value;
            }
        }
    }
}
