//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viridian.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class VirtualSystemSettingData : global::System.Configuration.ApplicationSettingsBase {
        
        private static VirtualSystemSettingData defaultInstance = ((VirtualSystemSettingData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VirtualSystemSettingData())));
        
        public static VirtualSystemSettingData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft:Hyper-V:System:Realized")]
        public string RealizedVirtualMachine {
            get {
                return ((string)(this["RealizedVirtualMachine"]));
            }
            set {
                this["RealizedVirtualMachine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft:Hyper-V:System:Planned")]
        public string PlannedVirtualMachine {
            get {
                return ((string)(this["PlannedVirtualMachine"]));
            }
            set {
                this["PlannedVirtualMachine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft:Hyper-V:Snapshot:Realized")]
        public string RealizedVirtualMachineSnapshot {
            get {
                return ((string)(this["RealizedVirtualMachineSnapshot"]));
            }
            set {
                this["RealizedVirtualMachineSnapshot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft:Hyper-V:Snapshot:Recovery")]
        public string RecoveryVirtualMachineSnapshot {
            get {
                return ((string)(this["RecoveryVirtualMachineSnapshot"]));
            }
            set {
                this["RecoveryVirtualMachineSnapshot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft:Hyper-V:Snapshot:Planned")]
        public string PlannedVirtualMachineSnapshot {
            get {
                return ((string)(this["PlannedVirtualMachineSnapshot"]));
            }
            set {
                this["PlannedVirtualMachineSnapshot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft:Hyper-V:Snapshot:Missing")]
        public string MissingSnapshot {
            get {
                return ((string)(this["MissingSnapshot"]));
            }
            set {
                this["MissingSnapshot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft:Hyper-V:Snapshot:Replica:Standard")]
        public string TimeBasedReplicationPointSnapshot {
            get {
                return ((string)(this["TimeBasedReplicationPointSnapshot"]));
            }
            set {
                this["TimeBasedReplicationPointSnapshot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft:Hyper-V:Snapshot:Replica:ApplicationConsistent")]
        public string VSSReplicationPointSnapshot {
            get {
                return ((string)(this["VSSReplicationPointSnapshot"]));
            }
            set {
                this["VSSReplicationPointSnapshot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft:Hyper-V:Snapshot:Replica:PlannedFailover")]
        public string PlannedReplicationSnapshot {
            get {
                return ((string)(this["PlannedReplicationSnapshot"]));
            }
            set {
                this["PlannedReplicationSnapshot"] = value;
            }
        }
    }
}
